(function () {
  var F = window.FPEM;
  var T = F.T;
  var MAX_STAMINA = F.MAX_STAMINA;
  var canvasEl = document.getElementById('game');
  var initialMap = 100;
  var initialMapPx = initialMap * T;
  var mazeCanvasEl = document.createElement('canvas');
  mazeCanvasEl.width = initialMapPx;
  mazeCanvasEl.height = initialMapPx;
  var bgMusic = new Audio('audio/audioprojectfpemaze.mp3');
  bgMusic.loop = true;
  bgMusic.volume = 0.5;
  F.state = {
    canvas: canvasEl,
    ctx: canvasEl.getContext('2d'),
    bgMusic: bgMusic,
    pausedAt: 0,
    MAP: initialMap,
    MAP_PX: initialMapPx,
    seed: undefined,
    hLines: [],
    vLines: [],
    rows: 0,
    cols: 0,
    map: undefined,
    hSegWall: undefined,
    vSegWall: undefined,
    startTX: undefined,
    startTY: undefined,
    exitTX: undefined,
    exitTY: undefined,
    mazeCanvas: mazeCanvasEl,
    mctx: mazeCanvasEl.getContext('2d'),
    gameState: 'menu',
    exitCorner: undefined,
    enemyVariant: undefined,
    EW: undefined,
    EH: undefined,
    BASE_ENEMY_SPEED: undefined,
    currentEnemySpeed: undefined,
    player: { x: 0, y: 0, dir: 0 },
    exitX: undefined,
    exitY: undefined,
    exitR: 3 * T,
    playerSlowed: false,
    playerStunned: false,
    stunTimer: 0,
    thavelStunCooldown: 0,
    bloomieState: 'ready',
    bloomieBoostTimer: 0,
    bloomieExhaustTimer: 0,
    bloomieCooldown: 0,
    enemy: { x: 0, y: 0, active: false, dir: 0 },
    enemyWaypoints: [],
    enemyWpIdx: 0,
    enemyMoving: false,
    won: false,
    lost: false,
    startTime: 0,
    elapsed: '0.0',
    roundPrepared: false,
    settingsStartLaunchesNewRound: false,
    stamina: MAX_STAMINA,
    sprinting: false,
    sprintExhausted: false,
    darknessEnabled: false,
    darknessRadiusTiles: 15,
    isDraggingSlider: false,
    itemsEnabled: true,
    oreoCount: 1,
    kitkatCount: 1,
    appleCount: 1,
    flashlightCount: 1,
    draggingItemSlider: -1,
    assignmentsEnabled: true,
    assignmentCount: 1,
    draggingAssignmentSlider: false,
    lockersEnabled: true,
    lockerCount: 1,
    draggingLockerSlider: false,
    mapSize: 100,
    draggingMapSlider: false,
    settingsScrollY: 0,
    enemyRepathTimer: 0,
    spriteAnimTimer: 0,
    spriteAnimFrame: 0,
    menuButtons: [
      { label: 'Tutorial', active: false },
      { label: 'Play', active: false },
      { label: 'Randomize', active: true },
      { label: 'Info', active: false }
    ],
    mouseX: 0,
    mouseY: 0,
    keys: {},
    lastTime: performance.now(),
    oreos: [],
    assignments: [],
    kitkats: [],
    apples: [],
    flashlights: [],
    lockers: [],
    playerInLocker: false,
    lockerTimer: 0,
    activeLockerIndex: -1,
    inventory: [null, null, null],
    invincible: false,
    invincibleTimers: [],
    invincibleStacks: 0,
    kitkatSlowTimers: [],
    flashlightTimers: [],
    kitkatSlowActive: false,
    flashlightActive: false,
    assignmentActive: false,
    assignmentA: 0,
    assignmentB: 0,
    assignmentAnswer: '',
    assignmentTimeLeft: 0,
    assignmentPausedAt: 0,
    assignmentPausedMs: 0,
    activeAssignment: null,
    assignmentsCompleted: 0,
    assignmentTeacherStunTimer: 0,
    assignmentTeacherBoostTimer: 0
  };
})();
